spring.application.name=todo-v1

spring.datasource.url=jdbc:${DB:postgresql}://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:todov1}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Winwin001!}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true