spring.application.name=todo-v1

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=admin
spring.datasource.password=Winwin001!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true